//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kima
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Evento
    {
        public int Id { get; set; }
        [Display(Name = "Color Evento")]
        public string color { get; set; }
        [Display(Name = "Nombre doctor")]
        public string doctor { get; set; }
        [Display(Name = "Anotaciones")]
        public string anotaciones { get; set; }
        [Display(Name = "Fecha Evento")]
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual CentroSalud CentroSalud { get; set; }
        public virtual Enfermedad Enfermedad { get; set; }
        public virtual Medicinas Medicina { get; set; }
    }
}
