//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Kima.Models
{
    using System;
    using System.Collections.Generic;

    public class Enfermedad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enfermedad()
        {
            this.Medicinas = new HashSet<Medicinas>();
            this.Eventoes = new HashSet<Evento>();
        }

        public int Id { get; set; }
        [Required]
        [Display(Name = "Nombre completo")]
        public string nombre { get; set; }
        [Display(Name = "Fecha de diágnostico")]
        public Nullable<System.DateTime> fecha_diagnostico { get; set; }
        [Display(Name = "Fecha del último evento de la enfermedad")]
        public Nullable<System.DateTime> ultimo_evento { get; set; }
        [Display(Name = "Tipo de la enfermedad (Crónico o no crónico)")]
        public string tipo { get; set; }

        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicinas> Medicinas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evento> Eventoes { get; set; }
    }
}
